### ISSUE TITLE
command line argument to parse files

### ISSUE THREAD

**Issue by Snupai** [SebiAi/GlyphVisualizer#4]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I've looked through the [README](https://github.com/SebiAi/GlyphVisualizer#readme)
- [X] I've verified that I have **updated GlyphVisualizer to the latest release version** ([latest version](https://github.com/SebiAi/GlyphVisualizer/releases/latest))
- [X] I've searched [known issues](https://github.com/SebiAi/GlyphVisualizer/issues?q=label%3Aenhancement) and the [roadmap](https://github.com/users/SebiAi/projects/5) for similar issues **including closed ones**. DO NOT post duplicates

### Provide a description that is worded well enough to be understood

Maybe add a command line argument to parse files to play right after the ui launched.
Could be combined with an auto close after finishing visualisation of the parsed audio.

**Comment by SebiAi** [comment]
Already on the roadmap, see [here](https://github.com/users/SebiAi/projects/5?pane=issue&itemId=46553659).
